_: {
  perSystem =
    { config, pkgs, ... }:
    {
      pre-commit.settings.hooks = {
        treefmt.enable = true;
        statix.enable = true;
        deadnix.enable = true;
        actionlint.enable = true;
        zizmor = {
          enable = true;
          args = [ "--offline" ];
        };
        oxlint = {
          enable = true;
          name = "oxlint";
          extraPackages = [ pkgs.nodejs_24 ]; # tsgolint (type-aware) needs node
          entry = toString (
            pkgs.writeShellScript "oxlint-entry" ''
              # astro:content etc. are virtual modules; their type declarations
              # (.astro/types.d.ts) are generated by `astro sync`, which also
              # writes its content-layer cache under node_modules/.astro/.
              # A plain `ln -sfn` of the whole node_modules to the (read-only)
              # nix store output would make those writes fail, so instead lay
              # out a writable node_modules directory whose entries are
              # symlinks into the cached store path (still no re-download).
              if [ ! -e node_modules ]; then
                mkdir node_modules
                shopt -s dotglob
                for entry in ${config.packages.nodeModules}/*; do
                  ln -s "$entry" "node_modules/$(basename "$entry")"
                done
              fi
              node_modules/.bin/astro sync
              exec ${pkgs.oxlint}/bin/oxlint
            ''
          );
          files = "\\.(ts|tsx|js|jsx)$";
          pass_filenames = false;
        };
        workflow-timeout = {
          enable = true;
          name = "Check workflow timeout-minutes";
          package = pkgs.check-jsonschema;
          entry = "${pkgs.check-jsonschema}/bin/check-jsonschema --builtin-schema github-workflows-require-timeout";
          files = "\\.github/workflows/.*\\.ya?ml$";
        };
      };
    };
}
