name: Test and Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
      - run: nix build
      - run: nix flake check

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'ps-blog'
          directory: 'dist'
          gitHubToken: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          wranglerVersion: "4.12.0"
